<?php

/**
 * AffiliateCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AffiliateCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AffiliateCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AffiliateCategory');
    }
}