<?php

/**
 * AssetCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetCategory');
    }
}