<?php

/**
 * CardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CardTable extends Doctrine_Table {

    const SORT_ASC = 'ASC';
    const SORT_DESC = 'DESC';

    public function addOrderByQuery($field = 'id', $sort = self::SORT_ASC, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Card c');
        }

        $alias = $q->getRootAlias();

        $q->orderBy($alias . '.' . $field . ' ' . $sort);

        return $q;
    }

    public function addByUserQuery($user, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Card c');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.user_id = ?', $user);

        return $q;
    }

    public function addByPromoQuery($promo, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Card c');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.promo_id = ?', $promo);

        return $q;
    }

    public function addByAlphaIdNotInQuery(array $alphaIds, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Card c');
        }

        $alias = $q->getRootAlias();

        $q->andWhereNotIn($alias . '.alpha_id', $alphaIds);

        return $q;
    }

    public function addByAlphaIdQuery($alphaId, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Card c');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.alpha_id = ?', $alphaId);

        return $q;
    }

    public function addByStatusQuery($status, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Card c');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.status = ?', $status);

        return $q;
    }

    public function addByStatusNotQuery($status, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Card c');
        }

        $alias = $q->getRootAlias();

        if (!is_array($status)) {
            $status = array($status);
        }

        $q->andWhereNotIn($alias . '.status', $status);

        return $q;
    }

    /**
     * Returns an instance of this class.
     *
     * @return object CardTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Card');
    }

}