<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    public function asArray() {
        return array(
                'id' => $this->getAlphaId(),
                'name' => $this->getName(),
                'type' => $this->getCategoryType()
            );
    }
    
    public function save(Doctrine_Connection $conn = null)
    {
        if (!$this->getAlphaId())
        {            
            $this->setAlphaId(Util::gen_uuid(hash('sha256',time().$this->getName().rand(11111, 99999))));
        }
        
        return parent::save($conn);
    }
}