<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table {

    public function addByTypeQuery($type = 'place', Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Category c');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.category_type = ?', $type);

        return $q;
    }

    public function addRootCategoriesQuery(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Category c');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.parent_id IS NULL');

        return $q;
    }

    public function addSubCategoriesQuery($category, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Category c');
        }

        $alias = $q->getRootAlias();

        $q->addWhere($alias . '.parent_id = ?', $category);

        return $q;
    }

    public function retrieveByCategoryType($type, $onlyRoots = true) {
        $q = $this->addByTypeQuery($type);

        if ($onlyRoots) {
            $q = $this->addRootCategoryQuery($q);
        }
        return $q->execute();
    }

    public function addWithActivePromosQuery(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Category c');
        }

        $alias = $q->getRootAlias();

        $q->leftJoin($alias.'.AffiliateCategory ac')
                ->leftJoin('ac.Affiliate a')
                ->leftJoin('a.Promos p')
                ->andWhere('p.starts_at <= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))))
                ->andWhere('p.expires_at >= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));

        return $q;
    }

    public function retrieveWithActivePromos($category = false, $type = false) {
        $q = Doctrine_Query::create()->from('Category c');

        if($type){
            $q = $this->addByTypeQuery($type, $q);
        }

        if (!$category) {
            $q = $this->addRootCategoriesQuery($q);
        } else {
            $q = $this->addSubCategoriesQuery($category, $q);
        }
        
        $q = $this->addWithActivePromosQuery($q);
        
        $q->orderBy('c.name');

        return $q->execute();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Category');
    }

}