<?php

/**
 * CouponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CouponTable extends Doctrine_Table
{
    /**
     * Retrieves a Coupon object by serial
     * 
     * @param string $serial
     * @param int $promo
     * @return Coupon 
     */
    public function retrieveBySerial($serial) 
    {
        $query = $this->addBySerialQuery($serial);

        return $query->fetchOne();
    }
    
    /**
     * Retrieves a Coupon object by serial and promo_id
     * 
     * @param string $serial
     * @param int $promo
     * @return Coupon 
     */
    public function retrieveBySerialAndPromo($serial, $promo) 
    {
        $query = $this->addBySerialQuery($serial, $this->addByPromoQuery($promo));

        return $query->fetchOne();
    }
    
    /**
     * Retrieves a Coupon object by serial, promo_id and status.
     * 
     * @param string $serial
     * @param int $promo
     * @param string $status
     * 
     * @return Coupon
     */
    public function retrieveBySerialAndPromoAndStauts($serial, $promo, $status = 'active') 
    {
        $query = $this->addBySerialQuery($serial, $this->addByPromoQuery($promo, $this->addByStatusQuery($status)));

        return $query->fetchOne();
    }
    
    public function addBySerialQuery($serial, Doctrine_Query $q = null )
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('Coupon c');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.serial = ?', $serial);
        
        return $q;
    }
    
    public function addBySerialLikeQuery($serial, Doctrine_Query $q = null )
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('Coupon c');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.serial LIKE ?', '%'.$serial.'%');
        
        return $q;
    }
    
    public function addByPromoQuery($promo, Doctrine_Query $q = null)
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('Coupon c');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.promo_id = ?', $promo);
        
        return $q;
    }
    
    public function addByStatusQuery($status = 'active', Doctrine_Query $q = null)
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('Coupon c');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.status = ?', $status);
        
        return $q;
    }
    
    public function addByCardQuery($card, Doctrine_Query $q = null)
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('Coupon c');
        }
        
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.card_id = ?', $card);
        
        return $q;
    }
    
    public function addByBeginDateQuery($date, Doctrine_Query $q = null)
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('Coupon c');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.used_at >= ?', $date);
        
        return $q;
    }
    
    public function addByEndDateQuery($date, Doctrine_Query $q = null)
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('Coupon c');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.used_at <= ?', $date);
        return $q;
    }
    
    public function findByCardIdQuery($card)
    {
        return $this->addByCardIdQuery($card)->execute();
    }
    
    public function addByUserProfileQuery($promo, $id_number, Doctrine_Query $q = null)
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('Coupon c');
        }
        $alias = $q->getRootAlias();
        
        $q->leftJoin($alias.'.User u');
        $q->leftJoin('u.UserProfile up');
        $q->andWhere($alias.'.promo_id = ?', $promo);
        $q->andWhere('up.id_number LIKE ?', '%'.$id_number.'%');
        
        return $q;
    }
    
    /**
     * Returns an instance of this class.
     *
     * @return object CouponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Coupon');
    }
}