<?php

/**
 * CurrencyAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurrencyAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CurrencyAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CurrencyAsset');
    }
}