<?php

/**
 * CurrencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurrencyTable extends Doctrine_Table
{
    public function retrieveMain()
    {
        $query = Doctrine::getTable('Currency')->createQuery('c')->where('c.is_super = 1');

        return $query->fetchOne();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object CurrencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Currency');
    }
}