<?php

/**
 * FeedbackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeedbackTable extends Doctrine_Table
{
    public function addOrderBy($field = 'created_at', $order = 'DESC', Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Feedback f');
        }
        
        $alias = $q->getRootAlias();
        
        $q->orderBy($alias.'.'.$field.' '.$order);
        
        return $q;
    }
    
    public function addByMessageQuery($str = '', $notEmpty = true, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Feedback f');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.message LIKE ?','%'.$str.'%');
        
        if($notEmpty){
            $q->andWhere($alias.'.message != ""');
        }
        
        return $q;
    }
    
    public function addByAffiliateQuery($affiliate, $order = 'DESC', Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Feedback f');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.affiliate_id = ?',$affiliate);
        
        $q->orderBy($alias.'.created_at '.$order);
        
        return $q;
    }
    
    public function addByAssetQuery($asset, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Feedback f');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.asset_id = ?',$asset);
        
        return $q;
    }
    
    public function addByValorationQuery($valoration, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Feedback f');
        }
        
        $alias = $q->getRootAlias();
        
        $q->addWhere($alias.'.valoration = ?',$valoration);
        
        return $q;
    }
    
    public function retrieveByAffiliate($affiliate, $valoration = -1, $order = 'DESC') {
        $q = $this->addByAffiliateQuery($affiliate, $order);
        
        if($valoration > -1){
            $q = $this->addByValorationQuery($valoration, $q);
        }
        
        return $q->execute();
    }
    
    public function retrieveLastComments($affiliate, $limit = 0, $order = 'DESC') {
        $q = $this->addByAffiliateQuery($affiliate, $order);
        
        $alias = $q->getRootAlias();
        
        $q->addWhere($alias.'.message != ""');
        
        if($limit > 0){
            $q->limit($limit);
        }
        
        return $q->execute();
    }
    
    public function retrieveAssetLastComments($asset, $limit = 0, $order = 'DESC') {
        $q = $this->addByAssetQuery($asset);
        $q = $this->addOrderBy('created_at', 'DESC', $q);
        
        $alias = $q->getRootAlias();
        
        $q->addWhere($alias.'.message != ""');
        
        if($limit > 0){
            $q->limit($limit);
        }
        
        return $q->execute();
    }
    
    public function retrieveLastCommentsByAsset($asset, $limit = 0, $order = 'DESC') {
        $q = $this->addByAssetQuery($asset);
        
        $alias = $q->getRootAlias();
        
        $q->addWhere($alias.'.message != ""');
        
        $q->orderBy($alias.'.created_at '.$order);
        
        if($limit > 0){
            $q->limit($limit);
        }
        
        return $q->execute();
    }
    
    public function countByAffiliate($affiliate, $valoration = -1) {
        $q = $this->addByAffiliateQuery($affiliate);
        
        if($valoration > -1){
            $q = $this->addByValorationQuery($valoration, $q);
        }
        
        return $q->count();
    }
    
    public function countByAsset($asset, $valoration = -1) {
        $q = $this->addByAssetQuery($asset);
        
        if($valoration > -1){
            $q = $this->addByValorationQuery($valoration, $q);
        }
        
        return $q->count();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object FeedbackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Feedback');
    }
}