<?php

/**
 * Flow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Flow extends BaseFlow
{
    public function save(Doctrine_Connection $conn = null) 
    {    
        $this->Pocket->setBalance($this->balance);
        
        return parent::save($conn);
    }
}