<?php

/**
 * FlowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlowTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FlowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Flow');
    }
}