<?php

/**
 * LicotecaUserLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LicotecaUserLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LicotecaUserLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LicotecaUserLevel');
    }
}