<?php

/**
 * MembershipCard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Jacobo Martinez <jacobo.amn87@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MembershipCard extends BaseMembershipCard
{
    public function hasStatus($status) 
    {
        return strcasecmp($status, $this->status) == 0;
    }
    
    public function save(Doctrine_Connection $conn = null) 
    {
        if (!$this->getAlphaId()) {
            $table = Doctrine::getTable('MembershipCard');
            $duplicated = true;
            
            $this->setAlphaId(Util::GenSecret(6, Util::CHAR_MIX));
            
            while ($duplicated) {
                if (!$table->findOneBy('alpha_id', $this->getAlphaId())) {
                    $duplicated = false;
                }
                else {
                    $this->setAlphaId(Util::GenSecret(6, Util::CHAR_MIX));
                }
            }
        }
        return parent::save($conn);
    }
}