<?php

/**
 * MembershipCardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MembershipCardTable extends Doctrine_Table {

    public function addByUserQuery($user, $is_virtual = false, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('MembershipCard mc');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.user_id = ?', $user);

        $q->andWhere($alias . '.is_virtual = ?', $is_virtual);

        return $q;
    }

    public function addByStatusQuery($status, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('MembershipCard mc');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.status = ?', $status);

        return $q;
    }

    public function addByAlphaIdQuery($alpha, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('MembershipCard mc');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.alpha_id = ?', $alpha);

        return $q;
    }

    public function retrieveUserMembershipCard($user, $is_virtual = false) {
        $q = $this->addByUserQuery($user, $is_virtual, $this->addByStatusQuery('active'));

        return $q->fetchOne();
    }
    
    public function retrieveByAlphaId($alpha) {
        $q = $this->addByAlphaIdQuery($alpha, $this->addByStatusQuery('active'));

        return $q->fetchOne();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object MembershipCardTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('MembershipCard');
    }

}