<?php

/**
 * MunicipalityCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MunicipalityCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MunicipalityCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MunicipalityCity');
    }
}