<?php

/**
 * ParticipationRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Jacobo Martinez <jacobo.amn87@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ParticipationRequest extends BaseParticipationRequest {
    
    protected $_secret = 'uJ01yW3Lo4IV8fIaUXVG';

    public function save(Doctrine_Connection $conn = null) {
        
        if (!$this->getHash()) {
            $this->setHash(hash('sha1', time() . rand(11111, 99999) . $this->_secret));
        }
        
        return parent::save($conn);
    }
    
}