<?php

/**
 * ParticipationRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParticipationRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParticipationRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParticipationRequest');
    }
}