<?php

/**
 * PocketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PocketTable extends Doctrine_Table
{
    /**
     * Retrieves a Pocket object by user_id and is_super flag.
     * 
     * @param integer $user
     * @param boolean $isSuper
     * 
     * @return Pocket 
     */
    public function retrieveUserMain($user, $isSuper = true)
    {
        $query = Doctrine_Query::create()
                    ->from('Pocket p')
                    ->andWhere('p.user_id = ?',$user)
                    ->andWhere('p.is_super = ?',$isSuper);

        return $query->fetchOne();
    }
    
    /**
     * Returns an instance of this class.
     *
     * @return object PocketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pocket');
    }
}