<?php

/**
 * PointsProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PointsProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PointsProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PointsProduct');
    }
}