<?php

/**
 * PromoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromoTable extends Doctrine_Table {

    public function addActivePromosQuery(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Promo p');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.starts_at <= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));
        $q->andWhere($alias . '.expires_at >= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));

        return $q;
    }
    
    public function addInExchangePeriodQuery(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Promo p');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.begins_at <= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));
        $q->andWhere($alias . '.expires_at >= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));

        return $q;
    }

    public function addByAffiliateQuery($affiliate, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Promo p');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.affiliate_id = ?', $affiliate);

        return $q;
    }

    public function addByAssetQuery($asset, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Promo p');
        }

        $alias = $q->getRootAlias();

        $q->leftJoin($alias . '.AssetPromo ap');

        $q->andWhere('ap.asset_id = ?', $asset);

        return $q;
    }

    public function addByAssetTypeQuery($assetType, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Promo p');
        }

        $alias = $q->getRootAlias();

        $q->leftJoin($alias . '.AssetPromo ap');
        $q->leftJoin($alias . '.Assets a');

        $q->andWhere('a.asset_type = ?', $assetType);

        return $q;
    }

    public function wawQuery() {
        $q = Doctrine_Query::create()->from('Promo p');

        $q = $this->addActivePromosQuery($q);

        $q = $this->addByAssetTypeQuery('place', $q);

        $alias = $q->getRootAlias();

        $q->leftJoin($alias . '.Affiliate af');

        $q->orderBy('af.name');

        return $q;
    }

    public function addByStatusQuery($status, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Promo p');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.status = ?', $status);

        return $q;
    }

    public function retrieveAffiliateActivePromos($affiliate) {
        return $this->addActivePromosQuery($this->addByAffiliateQuery($affiliate))->execute();
    }

    public function retrieveAssetPromos($asset, $onlyActive = false) {
        $q = $this->addByAssetQuery($asset);

        if ($onlyActive) {
            $q = $this->addActivePromosQuery($q);
        }
        return $q->execute();
    }
    
    public function getPromosQuery($active = true, $affiliate = false, $asset = false){
        $q = Doctrine_Query::create()->from('Promo p');
        
        if($active){
            $q = $this->addActivePromosQuery($q);
        }
        
        if($affiliate){
            $q = $this->addByAffiliateQuery($affiliate, $q);
        }
        
        if($asset){
            $q = $this->addByAssetQuery($asset, $q);
        }
        
        return $q;
    }
    
    public function getPromosInExchangePeriodQuery($affiliate, $asset){
        $q = Doctrine_Query::create()->from('Promo p');
        
        $q = $this->addInExchangePeriodQuery($q);
        $q = $this->addByAffiliateQuery($affiliate, $q);
        $q = $this->addByAssetQuery($asset, $q);
        
        return $q;
    }

    /**
     * Returns an instance of this class.
     *
     * @return object PromoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Promo');
    }

}