<?php

/**
 * PromoPrizeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromoPrizeTable extends Doctrine_Table {
    const ASC = 'ASC';
    const DESC = 'DESC';
    
    public function addByPromoQuery($promo, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoPrize pp');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.promo_id = ?', $promo);

        return $q;
    }
    
    public function addOrderByThresholdQuery($direction = 'ASC', Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoPrize pp');
        }

        $alias = $q->getRootAlias();

        $q->orderBy($alias.'.threshold '.$direction);

        return $q;
    }

    public function addByAlphaIdsQuery($ids, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoPrize pp');
        }

        $alias = $q->getRootAlias();

        $q->andWhereIn($alias . '.alpha_id', $ids);

        return $q;
    }

    public function retrieveByAlphaIds($ids) {
        return $this->addByAlphaIdsQuery($ids)->execute();
    }

    public function retrieveByPromo($promo, $ordered = false) {
        $q = $this->addByPromoQuery($promo);
        
        if ($ordered) {
            $q = $this->addOrderByThresholdQuery($ordered, $q);
        }
        
        return $q->execute();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object PromoPrizeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PromoPrize');
    }

}