<?php

/**
 * PromoPrize
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Jacobo Martinez <jacobo.amn87@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PromoPrize extends BasePromoPrize
{
    public function __toString() {
        return (string) $this->getPrize();
    }
    
    public function asArray($host = null) 
    {
        $prize = array(
            'id' => $this->getAlphaId(),
            'threshold' => $this->getThreshold(),
            'message' => $this->asMessage(),
            'prize' => $this->getPrize(),
            
        );
        
        $thumb = $this->getThumb() ? $this->getThumb() : $this->getPromo()->getThumb();
        
        if($thumb) {
            $prize['thumb'] = sfConfig::get('app_main_domain').'/uploads/'.$thumb;
        }
        
        return $prize;
    }
    
    public function asMessage() 
    {
        $message = $this->getThreshold().' Tag(s): '.$this->getPrize();
        
        return $message;
    }
    
    public function runOut() {
        if($this->getStock() == 0){
            return false;
        }
        
        return !($this->getStock() > $this->getDelivered());
    }

    public function save(Doctrine_Connection $conn = null)
    {
        if (!$this->getHash()) {
            $this->setHash(hash('sha256',time().rand(11111, 99999)));
        }
        
        if (!$this->getAlphaId()) {            
            $this->setAlphaId(Util::gen_uuid($this->getHash()));
        }
        
        return parent::save($conn);
    }
}