<?php

/**
 * PromoCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromoCodeTable extends Doctrine_Table {
    
    public function addByActivePromosQuery(Doctrine_Query $q = null){
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoCode pc');
        }
        
        $alias = $q->getRootAlias();
        
        $q->leftJoin($alias.'.Promo p');
        
        $q->andWhere('p.starts_at <= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));
        $q->andWhere('p.expires_at >= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));
        
        return $q;
    }
    
    public function addByActiveTagPeriodPromosQuery(Doctrine_Query $q = null){
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoCode pc');
        }
        
        $alias = $q->getRootAlias();
        
        $q->leftJoin($alias.'.Promo p');
        
        $q->andWhere('p.starts_at <= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));
        $q->andWhere('p.ends_at >= ?', date('Y-m-d H:i:s', mktime(0, 0, 0, date("m"), date("d"), date("Y"))));
        
        return $q;
    }
    
    public function addByAssetQuery($asset, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoCode pc');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.asset_id = ?', $asset);

        return $q;
    }

    public function addByPromoQuery($promo, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoCode pc');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.promo_id = ?', $promo);

        return $q;
    }

    public function addByCodeQuery($code, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoCode pc');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.alpha_id = ?', $code);

        return $q;
    }

    public function addByStatusQuery($status = 'active', Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoCode pc');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.status = ?', $status);

        return $q;
    }
    
    public function addByIsVirtualQuery($is_virtual, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('PromoCode pc');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.digital = ?', $is_virtual);

        return $q;
    }

    public function retrievePromoCode($code, $status = 'active', $digital = false) {
        $q = $this->addByCodeQuery($code, $this->addByStatusQuery($status));

        return $q->fetchOne();
    }
    
    public function getPromoCodeByAssetAndActiveTagPeriodPromosQuery($asset, $is_virtual = true){
        $q = $this->addByActiveTagPeriodPromosQuery();
        
        $q = $this->addByIsVirtualQuery($is_virtual, $q);
        
        return $this->addByAssetQuery($asset, $q);
    }

    /**
     * Returns an instance of this class.
     *
     * @return object PromoCodeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PromoCode');
    }

}