<?php

/**
 * PromoRedeemerConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromoRedeemerConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromoRedeemerConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PromoRedeemerConfig');
    }
}