<?php

/**
 * PromoCode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PromoCode extends BasePromoCode {

    public function getPromoName() {
        return $this->getPromo()->getName();
    }

    /**
     * Finds whether it has type "$type"
     * 
     * @param string $type
     * @return boolean
     */
    public function hasType($type = 'many_uses') {
        return strcasecmp($this->getType(), $type) == 0;
    }

    /**
     * Finds whether it has status "$status"
     * 
     * @param string $status
     * @return boolean
     */
    public function hasStatus($status) {
        return strcmp($this->getStatus(), $status) == 0;
    }

    /**
     * Finds whether it has status "active"
     * 
     * @return boolean 
     */
    public function isActive() {
        return $this->hasStatus('active');
    }
    
    public function countValidationCodes() {
        return $this->getValidationCodes()->count();
    }

    public function save(Doctrine_Connection $conn = null) {
        if (!$this->getHash()) {
            $this->setHash(hash('sha256', time().Util::GenSecret().rand(11111, 99999)));
        }
        
        if (!$this->getAlphaId()) {
            $this->setAlphaId(Util::gen_uuid($this->getHash()).($this->hasType('validation_required') ? 'VC' : ''));
        }

        return parent::save($conn);
    }
}