<?php

/**
 * PromoTermTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromoTermTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromoTermTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PromoTerm');
    }
}