<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
    /**
     * Returns 'New' if the user haven't activated his account, 'Reset' if the user
     * has requested for a password modification or false otherwise.
     * 
     * @return mixed string or boolean according to the cases above
     */
    public function getValidationType()
    {
        $t = substr($this->validate, 0, 1);
        
        if ($t == 'n')
        {
            return 'New';
        } 
        elseif ($t == 'r')
        {
            return 'Reset';
        }
        else
        {
            return false;
        }
    }
}