<?php

/**
 * StateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StateTable extends Doctrine_Table
{
    public function addByCountryQuery($country, Doctrine_Query $q = null)
    {
        if(is_null($q))
        {
            $q = Doctrine_Query::create()
                    ->from('State s');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.country_id = ?', $country);
        
        $q->orderBy('name');
        
        return $q;
    }

    /**
     * Returns an instance of this class.
     *
     * @return object StateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('State');
    }
}