<?php

/**
 * SubscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubscriptionTable extends Doctrine_Table
{
    public function addByUserQuery($user, Doctrine_Query $q = null)
    {
        if(is_null($q)){
            $q = Doctrine_Query::create()->from('Subscription s');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.user_id = ?', $user);
        
        return $q;
    }
    
    public function addByAffiliateQuery($affiliate, Doctrine_Query $q = null)
    {
        if(is_null($q)){
            $q = Doctrine_Query::create()->from('Subscription s');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.affiliate_id = ?', $affiliate);
        
        return $q;
    }
    
    public function addByAssetQuery($asset, Doctrine_Query $q = null)
    {
        if(is_null($q)){
            $q = Doctrine_Query::create()->from('Subscription s');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.asset_id = ?', $asset);
        
        return $q;
    }
    
    public function addByStatusQuery($status = 'active', Doctrine_Query $q = null)
    {
        if(is_null($q)){
            $q = Doctrine_Query::create()->from('Subscription s');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.status = ?', $status);
        
        return $q;
    }
    
    public function retrieveSubscription($user, $affiliate = null, $asset = null) 
    {
        $q = $this->addByUserQuery($user);
        
        if(!is_null($affiliate)){
            $q = $this->addByAffiliateQuery($affiliate, $q);
        }
        
        if(!is_null($asset)){
            $q = $this->addByAssetQuery($asset, $q);
        }
        
        return $q->fetchOne();
    }
    
    /**
     * Returns an instance of this class.
     *
     * @return object SubscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subscription');
    }
}