<?php

/**
 * SurveyItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyItemTable extends Doctrine_Table {
    
    public function addBySurveyQuery($survey, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('SurveyItem si');
        }
        
        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.survey_id = ?', $survey);

        return $q;
    }
    
    public function addByIsActiveFlagQuery($isActive = true, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('SurveyItem si');
        }
        
        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.is_active = ?', $isActive);

        return $q;
    }
    
    public function addOrderByPositionQuery(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('SurveyItem si');
        }
        
        $alias = $q->getRootAlias();

        $q->orderBy($alias.'.position ASC');

        return $q;
    }
    
    public function retrieveSurveyOrderedItems($survey, $activeOnly = true) {
        $q = $this->addBySurveyQuery($survey, $this->addOrderByPositionQuery());
        
        if ($activeOnly) {
            $q = $this->addByIsActiveFlagQuery(true, $q);
        }
        
        return $q->execute();
    }


    /**
     * Returns an instance of this class.
     *
     * @return object SurveyItemTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('SurveyItem');
    }

}