<?php

/**
 * SurveyParticipationRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyParticipationRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyParticipationRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyParticipationRequest');
    }
}