<?php

/**
 * SurveyApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Jacobo Martinez <jacobo.amn87@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SurveyApplication extends BaseSurveyApplication {
    public function getOrderedAnswers($itemsOrder) {
        $answersCollection = $this->getAnswers();
        
        $answers = array_fill(0, count($itemsOrder), '');
        
        foreach ($answersCollection as $answer) {
            $key = array_search($answer->getSurveyItemId(), $itemsOrder);
            
            if ($key !== false) {
                $answers[$key] = $answer->getFormatedAnswer();
            }
        }
        
        return $answers;
    }
    
    
}