<?php

/**
 * SurveyApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyApplicationTable extends Doctrine_Table {

    public function addBySurveyIdQuery($survey, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('SurveyApplication sa');
        }

        $alias = $q->getRootAlias();

        $q->addWhere($alias . '.survey_id = ?', $survey);

        return $q;
    }

    public function addByAssetsQuery($assets = null, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('SurveyApplication sa');
        }

        if (count($assets)) { //Si no hay assets, buscar para todos
            $alias = $q->getRootAlias();

            if (!is_array($assets)) {
                $assets = array($assets);
            }

            $q->andWhereIn($alias . '.asset_id', $assets);
        }

        return $q;
    }

    public function addUniqueUsersQuery(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('SurveyApplication sa');
        }

        $alias = $q->getRootAlias();
        
        $q->addSelect('DISTINCT '.$alias.'.user_id');
        
        return $q;
    }

    /**
     * Retrieve all the applications of a survey for a group of assets
     * @param mixed $asset  An array of assets id's or an asset id
     * @return SurveyApplication Collection 
     */
    public function retrieveBySurveyAndAssets($survey, $assets) {
        return $this->addBySurveyIdQuery($survey, $this->addByAssetsQuery($assets))->execute();
    }

    public function retriveUsersQuantityGroupByGenderAndAge($survey, $assets = null) {
        $query = "SELECT up.gender, FLOOR(DATEDIFF(NOW(),up.birthdate)/365.2425) as age, COUNT(DISTINCT up.user_id) as quantity FROM user_profile up LEFT JOIN survey_application sa ON sa.user_id = up.user_id WHERE up.gender NOT LIKE '' AND FLOOR(DATEDIFF(NOW(),up.birthdate)/365.2425) BETWEEN 8 AND 100 AND sa.survey_id = %survey_id% %ASSETS_COND% GROUP BY up.user_id, up.gender, age";
        
        $assetsCond = '';
        if (count($assets)) { //Si no hay assets, buscar para todos
            
            $assetsCond = 'AND sa.asset_id IN (%ids%)';
            
            if (!is_array($assets)) {
                $assets = array($assets);
            }
            
            $ids = '';
            $i = 0;
            $count = count($assets);
            foreach ($assets as $asset) {
                $ids = $ids.$asset;
                $i++;
                if ($count > $i) {
                    $ids = $ids.',';
                }
            }
            
            $assetsCond = str_replace(array('%ids%'), array($ids), $assetsCond);
        }
        
        $query = str_replace(array('%survey_id%','%ASSETS_COND%'), array($survey,$assetsCond), $query);
        
        $resultset = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($query);

        return $resultset;
    }

    /**
     * Returns an instance of this class.
     *
     * @return object SurveyApplicationTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('SurveyApplication');
    }

}