<?php

/**
 * SurveyItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Jacobo Martinez <jacobo.amn87@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SurveyItem extends BaseSurveyItem {
    protected $withOptionsTypes = array('multiple_selection','simple_selection','drop_list');
    
    public function usesOptions() {
        return in_array($this->getItemType(), $this->withOptionsTypes);
    }

    public function asArray($useAlphaId = false) {
        $array = array(
            'id' => $useAlphaId ? $this->getAlphaId() : $this->getId(),
            'type' => $this->getItemType(),
            'label' => $this->getLabel(),
            'help' => $this->getHelp(),
            'is_required' => $this->getIsRequired(),
            'position' => $this->getPosition(),
        );
        
        if ($this->usesOptions()) {
            $options = $this->getOptions();
            $opts = array();
            
            foreach ($options as $option) {
                $opts[($useAlphaId ? $option->getAlphaId() : $option->getId())] = $option->asArray($useAlphaId);
            }
            
            $array['options'] = $opts;
        }
        
        return $array;
    }
    
    public function save(Doctrine_Connection $conn = null) {
        if (!$this->getAlphaId()) {
            $this->setAlphaId(Util::gen_uuid(hash('sha256', time() . rand(11111, 99999))));
        }

        return parent::save($conn);
    }
}