<?php

/**
 * SurveyPromoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyPromoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyPromoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyPromo');
    }
}