<?php

/**
 * TdApiLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TdApiLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TdApiLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TdApiLog');
    }
}