<?php

/**
 * TicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketTable extends Doctrine_Table {

    public function addByCardIdQuery($card, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Ticket t');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.card_id = ?', $card);

        return $q;
    }

    public function addByUserQuery($user, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Ticket t');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.user_id = ?', $user);

        return $q;
    }

    public function addByPromoQuery($promo, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Ticket t');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.promo_id = ?', $promo);

        return $q;
    }

    public function addByPromoCodeQuery($promocode, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Ticket t');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.promo_code_id = ?', $promo);

        return $q;
    }

    public function countByCardId($card) {
        return $this->addByCardIdQuery($card)->count();
    }

    public function addByUsedQuery($used = false, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Ticket t');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.used = ?', $used);

        return $q;
    }

    public function addByCardAndUsedQuery($card, $used = false, Doctrine_Query $q = null) {
        return $this->addByCardIdQuery($card, $this->addByUsedQuery($used, $q));
    }

    public function getByUserAndPromoAndUsedQuery($user, $promo, $used = false) {
        return $this->addByUserQuery($user, $this->addByPromoQuery($promo, $this->addByUsedQuery($used)));
    }

    public function getByUserAndPromoQuery($user, $promo) {
        return $this->addByUserQuery($user, $this->addByPromoQuery($promo));
    }

    /**
     * Returns an instance of this class.
     *
     * @return object TicketTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Ticket');
    }

}