<?php

/**
 * Ticket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elperro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ticket extends BaseTicket {

    public function reset() {
        $this->free(true);
        $this->_data = $this->_table->getData();
        $this->_values = $this->cleanData($this->_data);
        foreach ((array) $this->_table->getIdentifier() as $id) {
            $this->_data[$id] = null;
        }
    }

}