<?php

/**
 * UserLicotecaUserLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserLicotecaUserLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserLicotecaUserLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserLicotecaUserLevel');
    }
}