<?php

/**
 * ValuePerActionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ValuePerActionTable extends Doctrine_Table
{
    
    public function retrieveByAction($action, $isSuper = true) {
        return $this->getInstance()->createQuery('vpa')
                ->where('vpa.action = ? AND vpa.is_super = ?', array($action,$isSuper))
                ->fetchOne();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object ValuePerActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ValuePerAction');
    }
}