<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Retrieves a sfGuardUser object by username.
     *
     * @param  string  $username The username
     * @param  boolean $isActive The user's status
     *
     * @return sfGuardUser
     */
    public function retrieveByUsernameWithoutActiveFlag($username) 
    {
        $query = Doctrine_Core::getTable('sfGuardUser')->createQuery('u')
                        ->where('u.username = ?', $username);

        return $query->fetchOne();
    }
    
    /**
     * Retrieves a sfGuardUser object by email.
     * 
     * @param string $email
     * @param boolean $isActive
     * 
     * @return sfGuardUser 
     */
    public function retrieveByEmail($email, $isActive = true)
    {
        $query = Doctrine_Core::getTable('sfGuardUser')->createQuery('u')->where('u.email_address = ?', $email);

        return $query->fetchOne();
    }
    
    /**
     * Retrieves a sfGuardUser object by username or email_address, it doesn't matter if it's active or not.
     *
     * @param  string  $username The username
     * @param  boolean $isActive The user's status
     *
     * @return sfGuardUser
     */
    public function retrieveByUsernameOrEmailAddressWithoutActiveFlag($username)
    {
        $query = Doctrine_Core::getTable('sfGuardUser')->createQuery('u')
                    ->where('u.username = ? OR u.email_address = ?', array($username, $username));

        return $query->fetchOne();
    }
  
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
}