generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ValidationCode
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          validation_code
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        batch_actions:
          _delete:  ~
          print:  ~
          assign: ~
        object_actions:
          _edit:  ~
          _delete:  ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
