# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            583e0fef3d86a7d45a36da4aa747d5b3a7b3d783

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS
    
    # Enable Internationalization
    i18n: on

    # Enable the database manager
    use_database:           true
    
    enabled_modules:      [default, sfGuardAuth, sdInteractiveChart, email]
    
    # Usado para definir las acciones de seguridad (sfDoctrineGuardPlugin)
    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure
