color:<?php echo '#' . (!empty($fontColor) ? $fontColor : '666666')?>;
display:block;
font-family:Arial;
font-size:32px;
font-weight:bold;
line-height:100%;
margin-top:0;
margin-right:0;
margin-bottom:10px;
margin-left:0;
text-align:left;